# Generated by Django 4.0.3 on 2022-04-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantswebsite', '0003_contactprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='plants',
            name='highlights_four',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='highlights_one',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='highlights_three',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='plants',
            name='highlights_two',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='contactprofile',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contactprofile',
            name='message',
            field=models.TextField(verbose_name='message'),
        ),
        migrations.AlterField(
            model_name='contactprofile',
            name='name',
            field=models.CharField(max_length=124, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='landingscreen',
            name='title',
            field=models.CharField(max_length=244, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='name',
            field=models.CharField(max_length=244, null=True),
        ),
        migrations.AlterField(
            model_name='plants',
            name='price',
            field=models.IntegerField(null=True),
        ),
    ]
