# Generated by Django 4.0.3 on 2022-07-06 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('plantswebsite', '0005_plantsorderitem_plantsorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='plantsorderitem',
            name='item',
        ),
        migrations.AddField(
            model_name='plants',
            name='quantity',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plants',
            name='status',
            field=models.BooleanField(default=False, help_text='0-default, 1-Hidden'),
        ),
        migrations.AddField(
            model_name='plants',
            name='trending',
            field=models.BooleanField(default=False, help_text='0-default, 1-Hidden'),
        ),
        migrations.DeleteModel(
            name='PlantsOrder',
        ),
        migrations.DeleteModel(
            name='PlantsOrderItem',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plantswebsite.plants'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
