# Generated by Django 4.0.3 on 2022-07-07 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plantswebsite', '0006_cart_remove_plantsorderitem_item_plants_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plants',
            name='price',
            field=models.FloatField(null=True),
        ),
    ]
